name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.7.1

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: programa          
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0 
      with: 
        username: bredimuliterno
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bredimuliterno/go_ci:${{github.run_number}}
